title: 수잘남 ːː 수리 잘하는 남자
description: 

url: http://issuehyo.github.com
baseurl: "/"
paginate_path: "page:num/"
permalink: :title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: issuehyo
  twitter: 
  facebook: 
  email: issuehyo@gmail.com
  linkedin: 

google_analytics: 

disqus:
    shortname: 
