title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://issuehyo.github.com
baseurl: "/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: issuehyo
  twitter: 
  facebook: 
  email: issuehyo@gmail.com
  linkedin: 

google_analytics: 

disqus:
    shortname: 
